### PR TITLE
Enable disabled tests for FVP target

### PR DESCRIPTION
**Pull request by mansnils**
This enables most unit tests that where previously disabled for this target.

BUG=This progress towards: https://github.com/tensorflow/tflite-micro/issues/274

### CODE REVIEW

**Comment by mansnils** [comment]
I am not sure why the code style fails. When running tensorflow/lite/micro/tools/ci_build/test_code_style.sh locally it does not complain about micro_error_reporter_test.cc.

**Comment by rockyrhodes** [comment]
When I run test_code_style.sh locally, I do see the same error.  It just wants a blank line between the 2 #include lines.

**Comment by advaitjain** [comment]
@mansnils, what version of clang-format are you using?

The CI uses clang-format-12: https://github.com/tensorflow/tflite-micro/blob/f75696cb9e7e5cc06761af2a83f7df0e5e975363/ci/Dockerfile.micro#L23

**Comment by mansnils** [comment]
That explains it. Thanks!

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
