### PR TITLE
lstm:xtensa:update colab link and model.zip

### PR DESCRIPTION
**Pull request by nyadla-sys**
BUG=cleanup

### CODE REVIEW

**Comment by nyadla-sys** [comment]
@advaitjain Please review and merge this #512  PR .
Updated colab links to point to tflite-micro github

**Review by advaitjain — CHANGES_REQUESTED** [review]
I don't think we should put in model.zip at all. We have the tflite files checked in already at https://github.com/tensorflow/tflite-micro/blob/main/third_party/xtensa/examples/micro_speech_lstm/micro_speech_lstm.tflite and it should be sufficient to link to that from the readme, right?

**Comment by nyadla-sys** [comment]
@advaitjain Sure,let me delete model.zip.
I guess  tflite file is sufficient

**Comment by nyadla-sys** [comment]
@advaitjain updated the same ,please review PR

**Comment by nyadla-sys** [comment]
@advaitjain Please approve this pR

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
