### PR TITLE
Quantize operator:

### PR DESCRIPTION
**Pull request by cad-audio**
Updated the quantize kernel to support all the data types similar to reference.
uncommented the test cases in quantize_test.

### CODE REVIEW

**Review by njeffrie — CHANGES_REQUESTED** [review]
Would it be possible to reuse the EvalQuantizeReference method rather than re-creating the logic in the xtensa quantize operator?

**Comment by freddan80** [comment]
@njeffrie @cad-audio would it be possible to add [uint8 support](https://github.com/tensorflow/tensorflow/blob/40670552faa92fb353bd0e4e5efed26979f239c5/tensorflow/lite/kernels/quantize.cc#L316) for this one op as an "exception"? We have received requests from customers for this feature since sensor data, e.g. images, usually comes as uint from the driver. That would remove the need to re-quantize in the app.

**Comment by freddan80** [comment]
Sorry for scope creeping this ticket... But I thought it was a good time to ask :)

**Comment by advaitjain** [comment]
Closing old PR. Let's reopen if needed.

**Pull request closed without merging**
