### PR TITLE
Pytorch to tflite conversion

### PR DESCRIPTION
**Pull request by nyadla-sys**
BUG=pytorch to tflite

### CODE REVIEW

**Comment by nyadla-sys** [comment]
@tingyan19 please review and merge this change

**Comment by tingyan19** [comment]
> @tingyan19 please review and merge this change

@nyadla-sys there seems to be a failed test - do you mind taking a look? Thanks.

**Comment by nyadla-sys** [comment]
> 

@tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue 
when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal 
And we are not sure  how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue

**Comment by tingyan19** [comment]
> > 
> 
> @tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal And we are not sure how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue

Can you try using "TARGET_ARCH=hifi4_internal" in your command line (instead of " TARGET_ARCH=hifi4") for your local build?

**Comment by nyadla-sys** [comment]
> > > 
> > 
> > 
> > @tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal And we are not sure how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue
> 
> Can you try using "TARGET_ARCH=hifi4_internal" in your command line (instead of " TARGET_ARCH=hifi4") for your local build?

I tried and getting below compilation issues
tensorflow/lite/micro/kernels/xtensa/add.cc:122:15: error: use of undeclared identifier 'xa_nn_elm_add_asym16sxasym16s_asym16s'; did you mean 'xa_nn_elm_add_asym8sxasym8s_asym8s'?
        err = xa_nn_elm_add_asym16sxasym16s_asym16s(
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              xa_nn_elm_add_asym8sxasym8s_asym8s
tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:8: note: 'xa_nn_elm_add_asym8sxasym8s_asym8s' declared here
WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * __restrict__ p_out,
       ^
tensorflow/lite/micro/kernels/xtensa/add.cc:123:13: error: cannot initialize a parameter of type 'WORD8 *' (aka 'signed char *') with an rvalue of type 'short *'
            tflite::micro::GetTensorData<int16_t>(output),
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:64: note: passing argument to parameter 'p_out' here
WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * __restrict__ p_out,
                                                               ^
tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc:83:21: error: use of undeclared identifier 'xa_nn_vec_leaky_relu_asym16s_asym16s'; did you mean 'xa_nn_vec_leaky_relu_asym8s_asym8s'?
      int32_t err = xa_nn_vec_leaky_relu_asym16s_asym16s(

**Comment by nyadla-sys** [comment]
> > > > 
> > > 
> > > 
> > > @tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal And we are not sure how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue
> > 
> > 
> > Can you try using "TARGET_ARCH=hifi4_internal" in your command line (instead of " TARGET_ARCH=hifi4") for your local build?
> 
> I tried and getting below compilation issues tensorflow/lite/micro/kernels/xtensa/add.cc:122:15: error: use of undeclared identifier 'xa_nn_elm_add_asym16sxasym16s_asym16s'; did you mean 'xa_nn_elm_add_asym8sxasym8s_asym8s'? err = xa_nn_elm_add_asym16sxasym16s_asym16s( ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ xa_nn_elm_add_asym8sxasym8s_asym8s tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:8: note: 'xa_nn_elm_add_asym8sxasym8s_asym8s' declared here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/add.cc:123:13: error: cannot initialize a parameter of type 'WORD8 *' (aka 'signed char *') with an rvalue of type 'short *' tflite::micro::GetTensorData<int16_t>(output), ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:64: note: passing argument to parameter 'p_out' here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc:83:21: error: use of undeclared identifier 'xa_nn_vec_leaky_relu_asym16s_asym16s'; did you mean 'xa_nn_vec_leaky_relu_asym8s_asym8s'? int32_t err = xa_nn_vec_leaky_relu_asym16s_asym16s(

Below is command I used
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=xtensa OPTIMIZED_KERNEL_DIR=xtensa TARGET=xtensa TARGET_ARCH=hifi4_internal test_pytorch_to_tflite_test -j

**Comment by tingyan19** [comment]
> > > > > 
> > > > 
> > > > 
> > > > @tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal And we are not sure how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue
> > > 
> > > 
> > > Can you try using "TARGET_ARCH=hifi4_internal" in your command line (instead of " TARGET_ARCH=hifi4") for your local build?
> > 
> > 
> > I tried and getting below compilation issues tensorflow/lite/micro/kernels/xtensa/add.cc:122:15: error: use of undeclared identifier 'xa_nn_elm_add_asym16sxasym16s_asym16s'; did you mean 'xa_nn_elm_add_asym8sxasym8s_asym8s'? err = xa_nn_elm_add_asym16sxasym16s_asym16s( ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ xa_nn_elm_add_asym8sxasym8s_asym8s tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:8: note: 'xa_nn_elm_add_asym8sxasym8s_asym8s' declared here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/add.cc:123:13: error: cannot initialize a parameter of type 'WORD8 *' (aka 'signed char *') with an rvalue of type 'short *' tflite::micro::GetTensorData<int16_t>(output), ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:64: note: passing argument to parameter 'p_out' here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc:83:21: error: use of undeclared identifier 'xa_nn_vec_leaky_relu_asym16s_asym16s'; did you mean 'xa_nn_vec_leaky_relu_asym8s_asym8s'? int32_t err = xa_nn_vec_leaky_relu_asym16s_asym16s(
> 
> Below command I used make -f tensorflow/lite/micro/tools/make/Makefile TARGET=xtensa OPTIMIZED_KERNEL_DIR=xtensa TARGET=xtensa TARGET_ARCH=hifi4_internal test_pytorch_to_tflite_test -j

@nyadla-sys 

I changed https://github.com/tensorflow/tflite-micro/blob/d817b58c601175bc6a503fa7f67fe3668bf53b21/tensorflow/lite/micro/kernels/xtensa/pad.cc#L239-L240 to

      TF_LITE_KERNEL_LOG(context, "Type %d not currently supported by Pad.",
                         input->type);

and (without using hifi4_internal) I got:

input->dims->size:4
input->dims->data[0]:1
input->dims->data[1]:3
input->dims->data[2]:224
input->dims->data[3]:224
input->type:9
input->bytes:150528
Type -387389208 not currently supported by Pad.
Node PAD (number 3) failed to invoke with status 1
Invoke failed


It seems like there is an invalid type number was produced. This should have nothing to do with hifi4_internal. 

Can you try and see if you can reproduce this?

**Comment by nyadla-sys** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > @tingyan19 Looks like it uses HiFi4_INTERNAL flag as part of xtensa/Pad.cc and this seems to be causing the issue when we test in our local build for fusionf1/hifi4/hifi5 it works fine as it does not use HiFi4_Internal And we are not sure how to enable HiFi4_INTERNAL flag as part of our local build to reproduce the issue
> > > > 
> > > > 
> > > > Can you try using "TARGET_ARCH=hifi4_internal" in your command line (instead of " TARGET_ARCH=hifi4") for your local build?
> > > 
> > > 
> > > I tried and getting below compilation issues tensorflow/lite/micro/kernels/xtensa/add.cc:122:15: error: use of undeclared identifier 'xa_nn_elm_add_asym16sxasym16s_asym16s'; did you mean 'xa_nn_elm_add_asym8sxasym8s_asym8s'? err = xa_nn_elm_add_asym16sxasym16s_asym16s( ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ xa_nn_elm_add_asym8sxasym8s_asym8s tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:8: note: 'xa_nn_elm_add_asym8sxasym8s_asym8s' declared here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/add.cc:123:13: error: cannot initialize a parameter of type 'WORD8 *' (aka 'signed char *') with an rvalue of type 'short *' tflite::micro::GetTensorData<int16_t>(output), ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi4/include/nnlib/xa_nnlib_kernels_api.h:1754:64: note: passing argument to parameter 'p_out' here WORD32 xa_nn_elm_add_asym8sxasym8s_asym8s(WORD8 * **restrict** p_out, ^ tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc:83:21: error: use of undeclared identifier 'xa_nn_vec_leaky_relu_asym16s_asym16s'; did you mean 'xa_nn_vec_leaky_relu_asym8s_asym8s'? int32_t err = xa_nn_vec_leaky_relu_asym16s_asym16s(
> > 
> > 
> > Below command I used make -f tensorflow/lite/micro/tools/make/Makefile TARGET=xtensa OPTIMIZED_KERNEL_DIR=xtensa TARGET=xtensa TARGET_ARCH=hifi4_internal test_pytorch_to_tflite_test -j
> 
> @nyadla-sys
> 
> I changed
> 
> https://github.com/tensorflow/tflite-micro/blob/d817b58c601175bc6a503fa7f67fe3668bf53b21/tensorflow/lite/micro/kernels/xtensa/pad.cc#L239-L240
> 
> to
> ```
>   TF_LITE_KERNEL_LOG(context, "Type %d not currently supported by Pad.",
>                      input->type);
> ```
> 
> and (without using hifi4_internal) I got:
> 
> input->dims->size:4 input->dims->data[0]:1 input->dims->data[1]:3 input->dims->data[2]:224 input->dims->data[3]:224 input->type:9 input->bytes:150528 Type -387389208 not currently supported by Pad. Node PAD (number 3) failed to invoke with status 1 Invoke failed
> 
> It seems like there is an invalid type number was produced. This should have nothing to do with hifi4_internal.
> 
> Can you try and see if you can reproduce this?

@tingyan19 I tried on our local server with hifi4 and hifi5 core config and it works fine..
lets discuss more details in our calls

**Review by tingyan19 — APPROVED** [review]

**Pull request merged**
