### PR TITLE
Convolution kernel wrappers now accept nullptr bias tensors.

### PR DESCRIPTION
**Pull request by keandersslab**
This solves https://github.com/tensorflow/tflite-micro/issues/706

### CODE REVIEW

**Comment by keandersslab** [comment]
Time for review soon ?

**Comment by kjeir** [comment]
Hi.
This PR has been in review for 5 months now. Does somebody have an oppurtunity to have a look ? 
Thanks

**Comment by paulinesho** [comment]
Hi @kjeir the team discussed this issue today and preferred to go with this approach instead: https://github.com/tensorflow/tflite-micro/pull/1114. We think that using `GetOptionalTensorData` introduced in that PR will make it more explicit about what behavior is intended and hence more readable. Let me know if we can close this or if there's any other issue.

**Comment by keandersslab** [comment]
I agree that #1114 is a better solution.
I will close this PR

**Comment by keandersslab** [comment]
Solved by #1114

**Pull request closed without merging**
