### PR TITLE
exempt Arm(R) Cortex(R)-M-based builds from string overread warning

### PR DESCRIPTION
**Pull request by annietllnd**
BUG=#1571

Using the [filter](https://www.gnu.org/software/make/manual/html_node/Text-Functions.html) function instead, we are able to filter out all builds where this issue has been seen

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
Just confirming, is this still needed after https://github.com/tensorflow/tflite-micro/pull/1550?

**Comment by advaitjain** [comment]
> Just confirming, is this still needed after #1550?

What I should have asked is that if we remove `Wno-stringop-overread` are we ok? Since #1550 fixes the warning, we can go ahead and revert #1544

**Comment by annietllnd** [comment]
Hi Advait, yes that's also an option. If you're okay with reverting #1544, then let's do that. Thanks!

**Comment by advaitjain** [comment]
> Hi Advait, yes that's also an option. If you're okay with reverting #1544, then let's do that. Thanks!

Reverting with https://github.com/tensorflow/tflite-micro/pull/1577

**Pull request closed without merging**
