### PR TITLE
Add README instructions for generating projects for cortex m generic, ensure include paths are added to cortex_m_generic makefile

### PR DESCRIPTION
**Pull request by cdknorow**
cortex-m-generic and CMSIS, update makefile to ensure Include paths for CMSIS
are added to the project file

### CODE REVIEW

**Comment by cdknorow** [comment]
@advaitjain this is kind of hackish, not sure if its worth adding, but I felt I'd make a pull request anyway

**Comment by cdknorow** [comment]
@googlebot I consent

**Comment by advaitjain** [comment]
> @advaitjain this is kind of hackish, not sure if its worth adding, but I felt I'd make a pull request anyway

My hope is that you can switch to using the new project generation fairly easily. I would prefer having you switch over to that rather than fixing the makefile based generation (or adding in additional documentation for it).

It is also part of our CI so we have more guarantees that future updates will not break that workflow:
https://github.com/tensorflow/tflite-micro/blob/a9f2e03b943990bc958ce3b92ca76ffc27fcf6d6/tensorflow/lite/micro/tools/ci_build/test_project_generation.sh#L57-L69

**Comment by cdknorow** [comment]
@advaitjain got it, I'll look into that next.

**Pull request closed without merging**
