### PR TITLE
XTENSA_CODE_REFACTOR: depthwise_conv

### PR DESCRIPTION
**Pull request by cad-audio**
Refactored the xtensa hifi optimized code for depthwise_conv operator.

BUG=refactoring existing code.

### CODE REVIEW

**Review by advaitjain — DISMISSED** [review]

**Comment by advaitjain** [comment]
@bhanuprakashbv if you can confirm 

> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 

@bhanuprakashbv, if you can reply with @googlebot  I consent, then we can get this PR merged.

**Comment by cad-audio** [comment]
@googlebot I consent

**Comment by advaitjain** [comment]
> @googlebot I consent

This needs to come from the @bhanuprakashbv github account. Basically, the CLA-bot has recognized all the CLAs, but the author of the commit (@bhanuprakashbv) is different from the PR author (@cad-audio).

**Review by advaitjain — APPROVED** [review]

**Comment by bhanuprakashbv** [comment]
@googlebot I consent

**Pull request merged**
