### PR TITLE
Replace tensorflow-cpu usage with tensorflow

### PR DESCRIPTION
**Pull request by rascani**
The tensorflow-cpu package does not support MacOS or non-x86 hardware. Replacing the tensorflow-cpu python package requirement with the tensorflow meta package should enable the bazel build and the dependent python scripts to be used on those platforms.

BUG=#2367, #1781

### CODE REVIEW

**Comment by kismeter** [comment]
bazel build tensorflow/lite/micro/examples/micro_speech:audio_preprocessor not working on macos with the patch

**Comment by rascani** [comment]
Thanks @kismeter. Could you provide output log?

**Comment by kismeter** [comment]
> Thanks @kismeter. Could you provide output log?
here's the logs
`
tflite-micro % bazel build tensorflow/lite/micro/examples/micro_speech:audio_preprocessor

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_alpha/bfbcf8515a0c85a3ab85982eec0435fb/external/tensorflow_cc_deps/BUILD", line 7, column 16, in <toplevel>
		hdrs = glob(["_site/tensorflow/include/**"], allow_empty=False, exclude_directories=1),
Error in glob: glob pattern '_site/tensorflow/include/**' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: /private/var/tmp/_bazel_alpha/bfbcf8515a0c85a3ab85982eec0435fb/external/tensorflow_cc_deps/BUILD: no such target '@@tensorflow_cc_deps//:cc_library': target 'cc_library' not declared in package '' defined by /private/var/tmp/_bazel_alpha/bfbcf8515a0c85a3ab85982eec0435fb/external/tensorflow_cc_deps/BUILD (Tip: use `query "@tensorflow_cc_deps//:*"` to see all the targets in that package)
ERROR: /Users/alpha/tflite-micro/python/tflite_micro/signal/BUILD:283:23: no such target '@@tensorflow_cc_deps//:cc_library': target 'cc_library' not declared in package '' defined by /private/var/tmp/_bazel_alpha/bfbcf8515a0c85a3ab85982eec0435fb/external/tensorflow_cc_deps/BUILD (Tip: use `query "@tensorflow_cc_deps//:*"` to see all the targets in that package) and referenced by '//python/tflite_micro/signal:ops/_window_op.so'
ERROR: Analysis of target '//tensorflow/lite/micro/examples/micro_speech:audio_preprocessor' failed; build aborted: Analysis failed
INFO: Elapsed time: 27.010s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@tflm_pip_deps_numpy; starting 8s
    Fetching repository @@numpy_cc_deps; Restarting.
    Fetching repository @@tflm_pip_deps_tensorflow_macos; starting
`

**Comment by mansnils** [comment]
Hi @kismeter, Is it working on Mac OS now?

**Review by mansnils — APPROVED** [review]

**Comment by kismeter** [comment]
> Hi @kismeter, Is it working on Mac OS now?

@mansnils build passed.
Running audio_preprocessor crash on apple silicon macOS due to other issue.

**Review by suleshahid — APPROVED** [review]

**Pull request merged**
