### PR TITLE
build(bazel): add --//:with_compression build setting

### PR DESCRIPTION
**Pull request by rkuester**
Add a --//:with_compression user-defined build setting and a
corresponding configuration setting.

Among other things, this will be used by Bazel in the future to
define the preprocessor macro USE_TFLM_COMPRESSION,
turning on conditional compilation of the compression feature.

BUG=#2636

### CODE REVIEW

**Comment by suleshahid** [comment]
Just to add some more info to the PR, could you add to the PR description the equivalent MAKE flag/define this will be enabling.

**Comment by suleshahid** [comment]
cortex-m failures from this? seems different error from the other bug, but not sure why

**Comment by rkuester** [comment]
> Just to add some more info to the PR, could you add to the PR description the equivalent MAKE flag/define this will be enabling.

Description updated.

**Review by suleshahid — APPROVED** [review]

**Comment by rkuester** [comment]
@Mergifyio refresh

**Comment by suleshahid** [comment]
https://github.com/Mergifyio refresh

**Comment by rkuester** [comment]
@Mergifyio refresh

**Comment by rkuester** [comment]
@mergifyio refresh

**Comment by suleshahid** [comment]
https://github.com/Mergifyio refresh

**Pull request merged**
