### PR TITLE
Updated conv kernel to use function specializations and bug fixes for ARC.

### PR DESCRIPTION
**Pull request by gerbauz**
This PR brings convolution kernel update for ARC target.

BUG=#719

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated branch. Waiting for merge.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Pull request merged**
