### PR TITLE
Fix build issues for variants of TARGET_ARCH=cortex-m7+fp

### PR DESCRIPTION
**Pull request by mansnils**
BUG=fixes https://github.com/tensorflow/tflite-micro/issues/1356

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
@Mergifyio refresh

**Comment by advaitjain** [comment]
@mansnils: this PR is not getting merged by our merge queue (mergify), likely because it is a draft PR.

**Comment by mansnils** [comment]
@advaitjain It got merged after all, thanks!

**Comment by advaitjain** [comment]
> @advaitjain It got merged after all, thanks!

Yes, I have to manually add a comment to get mergify to move the PR along. It would be helpful for me if that extra step can be avoided for future PRs.

**Comment by mansnils** [comment]
> > @advaitjain It got merged after all, thanks!
> 
> Yes, I have to manually add a comment to get mergify to move the PR along. It would be helpful for me if that extra step can be avoided for future PRs.

I am not sure what the problem was about. Please let me know if I should do things differently for future PRs.

**Pull request merged**
