### PR TITLE
Updates the CI for Cortex-M with Arm Compiler 6.

### PR DESCRIPTION
**Pull request by Evagan2018**
This PR updates the CI for Cortex-M with Arm Compiler 6. It replaces the workflow from:
https://github.com/tensorflow/tflite-micro/blob/main/.github/workflows/cortex_m_virtual_hardware.yml
that required updating. The new workflow is simplified and can run on Github runners directly.

BUG="Fixing CI for Arm Compiler 6"

### CODE REVIEW

**Comment by mansnils** [comment]
For more context. This is the previous PR: https://github.com/tensorflow/tflite-micro/pull/2479

**Review by sirakiin — APPROVED** [review]
Thanks for the PR.

**Comment by suleshahid** [comment]
Thanks for the PR. Some PR approval requirements, could you sign the CLA and update. Also could you add a BUG=<bug link or some one line summary>.

**Comment by Evagan2018** [comment]
I am on ARM's CLA now. Added the Bug information to the PR description. Let me know if something else is missing.

**Comment by suleshahid** [comment]
Hm, I triggered re-scan, but still doesn't seem to recognize on CLA, could you check the links in the failure?

**Comment by suleshahid** [comment]
I see its green for PR opener, but red for the author email. Going to approve and see.

**Review by suleshahid — APPROVED** [review]

**Comment by suleshahid** [comment]
Seems like still needs CLA for `Author: <E***7​@git>`

**Comment by Evagan2018** [comment]
> Seems like still needs CLA for `Author: <E***7​@git>`

Thanks for your feedback and approval. We analysed this, and it seems to be a wrong setting from the git client, the original commit was made with. Do we need to raise the PR again, with a proper Author setting, or can this still be merged?

**Comment by suleshahid** [comment]
Yes, could you raise a new PR, the CLA check is unfortunately blocking submit as a needed requirement. Thanks.

**Comment by Evagan2018** [comment]
This PR has been replaced with:
https://github.com/tensorflow/tflite-micro/pull/2771

**Pull request closed without merging**
