### PR TITLE
Added micro_speech_mock example files for create_tflm_tree.py script.

### PR DESCRIPTION
**Pull request by gerbauz**
For ARC we used "micro speech mock" example. This small fix adding ability to use 
`python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py ... -e micro_speech_mock ...` to generate directory tree with sources for this example.

BUG=#637

### CODE REVIEW

**Comment by gerbauz** [comment]
Updated.

**Review by deqiangc — APPROVED** [review]

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Pull request merged**
