### PR TITLE
Update CMSIS third party download

### PR DESCRIPTION
**Pull request by mansnils**
CMSIS is updated from CMSIS_5 to CMSIS_6.

BUG=It is recommended to upgrade from CMSIS_5 to CMSIS_6

### CODE REVIEW

**Review by rascani — APPROVED** [review]

**Comment by mansnils** [comment]
@Mergifyio refresh

**Comment by ddavis-2015** [comment]
@mansnils gotta wait for @suleshahid to get this merged

**Review by suleshahid — APPROVED** [review]

**Comment by mansnils** [comment]
@Mergifyio refresh

**Comment by mansnils** [comment]
@Mergifyio refresh

**Comment by suleshahid** [comment]
Found some error message from mergify from previous CI, this may the culprit to why mergify isn't merging this anymore:


>The configuration uses the deprecated commit_message_template attribute of the queue action in one or more pull_request_rules. It must now be used under the queue_rules configuration.
A brownout is planned on September 16th, 2024.
This option will be removed on October 21st, 2024.
For more information: https://docs.mergify.com/configuration/file-format/#queue-rules

**Comment by suleshahid** [comment]
https://github.com/Mergifyio refresh

**Pull request merged**
