### PR TITLE
Update RISCV workflows to use docker container with qemu.

### PR DESCRIPTION
**Pull request by advaitjain**
This is a first step towards switching RISCV CI to using qemu instead of Renode.

qemu build and install takes a long time, so we currently use it via the TFLM CI docker container (#1904).

Once this PR is merged, #2035 should be ready to go.

Note that changes to the GitHub workflows can not be fully tested until they are merged. I manually triggered the continuous build from my fork of tflite-micro to catch any obvious errors: https://github.com/advaitjain/tflite-micro/actions/runs/5247123996

BUG=http://b/286622884#comment5

### CODE REVIEW

**Comment by advaitjain** [comment]
Once https://github.com/tensorflow/tflite-micro/pull/2042 is merged, I will update this PR and add @rascani  as a reviewer.

**Comment by advaitjain** [comment]
> Once #2042 is merged, I will update this PR and add @rascani as a reviewer.

ready for review.

**Review by rascani — APPROVED** [review]

**Comment by advaitjain** [comment]
@mergifyio refresh

**Comment by advaitjain** [comment]
@mergifyio refresh

**Pull request merged**
