### PR TITLE
Update link to point to new tf-lite micro repo

### PR DESCRIPTION
**Pull request by silabs-LudvigS**

### CODE REVIEW

**Comment by petewarden** [comment]
Thanks for spotting this problem! I've filed bug #324 to cover the wider issues here, since I think we'll need some additional fixes (for example the line `cp -r tensorflow/tensorflow/lite/micro/examples/magic_wand/train train` will need to be updated too, I think).

Are you able to sign the code license agreement? If there are any issues, please get in touch with me through petewarden@google.com.

**Comment by silabs-LudvigS** [comment]
@googlebot I signed it!

**Comment by silabs-LudvigS** [comment]
@googlebot I signed it!

**Review by advaitjain — APPROVED** [review]

**Comment by silabs-LudvigS** [comment]
@googlebot I signed it!

**Comment by silabs-LudvigS** [comment]
@googlebot I fixed it.

**Comment by silabs-LudvigS** [comment]
@googlebot I fixed it.

**Comment by advaitjain** [comment]
Apologies that getting the CLA accepted is turning out to be somewhat complex for you. I have manually verified that your CLA is being recognized correctly. The challenge right now is that it appears that one of the merges did not happen cleanly and so the automation needs author consent from a number of additional users.

I would recommend creating a new PR.

And also use the steps [documented here](https://github.com/tensorflow/tflite-micro/blob/main/CONTRIBUTING.md#during-the-pr-review) to merge main into your branch:
```
git remote add upstream https://github.com/tensorflow/tflite-micro.git
git fetch upstream
git merge upstream/main
```

**Pull request closed without merging**
