### PR TITLE
Modified Espressif Dev boards build badge to include ESP32-S3

### PR DESCRIPTION
**Pull request by vikramdattu**
The new badge now looks like this:
Screenshot 2022-05-11 at 5 38 13 PM

BUG=

### CODE REVIEW

**Review by advaitjain — CHANGES_REQUESTED** [review]
I would prefer having a single build badge for the tflite-micro-esp-examples repo that is green if all the workflows pass. That would avoid having to update the badges in the TFLM repo each time there is a change in the Espressif repo.

Thoughts on how that might be implemented?

**Comment by vikramdattu** [comment]
@advaitjain I will check this. To achieve this, I think, composite actions might help.

**Comment by vikramdattu** [comment]
Hi @advaitjain please check the updated MR.
For ESP, I now use reusable actions to gather board building under single `ci.yml`

**Comment by advaitjain** [comment]
Is this still something you would like to merge? I'm closing but feel free to reopen.

**Comment by vikramdattu** [comment]
@advaitjain the change is definitely needed. I will rebase and reopen the PR.

**Comment by vikramdattu** [comment]
Hi @advaitjain please re-open the MR and take the change. Thanks.

**Comment by advaitjain** [comment]
I can't reopen this PR. Can you please create a new one? Thanks.

**Comment by vikramdattu** [comment]
> I can't reopen this PR. Can you please create a new one? Thanks.

@advaitjain done! https://github.com/tensorflow/tflite-micro/pull/1403

**Pull request closed without merging**
