### PR TITLE
Cadence:Implemented C ref for Sigmoid and Tanh

### PR DESCRIPTION
**Pull request by nyadla-sys**
Higher accuracy Fixed point implementation for Sigmoid and Tanh are
implemented.
-	Exp(-x) function is implemented with 4th order polynomial
	approximation
-	Division by newton Raphson method of approximation

BUG=https://github.com/tensorflow/tflite-micro/issues/286

Signed-off-by:Lukman Rahumathulla <lukmanr@cadence.com>

### CODE REVIEW

**Comment by nyadla-sys** [comment]
@googlebot I signed it!

**Comment by nyadla-sys** [comment]
@googlebot I signed it!

**Comment by petewarden** [comment]
Thanks for this! The code changes make sense, but there are a few issues:

 - There's a Cadence copyright notice added at the start, which we'll need removed before we can accept the change.
 - It's touching a file shared by TFLite mobile and Micro, so the PR will need to be submitted to the github.com/tensorflow/tensorflow repo instead, and then synced over.
 - It looks like there are some CLA problems, let us know if you are still stuck resolving them.

**Comment by nyadla-sys** [comment]
Need to update copyright

**Pull request closed without merging**
