### PR TITLE
build: update python_rules to support Python 3.12

### PR DESCRIPTION
**Pull request by LucasChollet**
Before, when trying to use to build the project using Bazel, this would result in multiple occurrence of this error:
`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`

This error is due to `rules_python` being too old. While building with Python3.12 still result in an error, the new one clearly indicate is mismatch of the TensorFlow version.

Very similar/related: https://github.com/googleapis/gapic-generator-python/pull/1825

BUG=https://github.com/tensorflow/tensorflow/issues/73174

### CODE REVIEW

**Comment by LucasChollet** [comment]
I used the link in the documentation to open an issue, no sure if it was correct to open it in the main tensorflow repository. Let me know if I should create a new one in `tflite-micro`.

**Review by rascani — APPROVED** [review]

**Comment by LucasChollet** [comment]
Thanks for the approval!
Seems that there is a mergify issue though and I'm not sure what am I suppose to do.
Should I just update my branch by merging `tensorflow:main` into my branch? Or is it because I inattentively used the `main` branch of my fork to create the PR? (In this case I think I will need to create another PR)
Anyway, I'm waiting on your input to avoid doing something wrong.

**Comment by rascani** [comment]
> Thanks for the approval! Seems that there is a mergify issue though and I'm not sure what am I suppose to do. Should I just update my branch by merging `tensorflow:main` into my branch? Or is it because I inattentively used the `main` branch of my fork to create the PR? (In this case I think I will need to create another PR) Anyway, I'm waiting on your input to avoid doing something wrong.

Sometimes this happens when we try to merge a bunch of PRs at once. I've updated the branch and that should kick off a fresh attempt.

**Comment by LucasChollet** [comment]
@rascani
Hmm, do you have to approve it again or something?

**Comment by LucasChollet** [comment]
Thanks!

**Pull request merged**
