### PR TITLE
Added Model Adaptation Tool to use with embARC MLI Library 2.0 for ARC

### PR DESCRIPTION
**Pull request by gerbauz**
[10/11]

This PR adds ARC specific Model Adaptation Tool required for new MLI 2.0 layout.

BUG=#86

### CODE REVIEW

**Comment by advaitjain** [comment]
We recently added Python formatting to the Code Style checks. Instructions on how to get that set up are at: https://github.com/tensorflow/tflite-micro/blob/main/CONTRIBUTING.md#initial-setup

You can fix all the formatting errors with:
```
tensorflow/lite/micro/tools/ci_build/test_code_style.sh --fix_formatting
```

Please note that you should delete the pigweed folder prior to trying this out:
```
rm -rf tensorflow/lite/micro/tools/make/downloads/pigweed
```

and add a pre-push hook with
```
cp tensorflow/lite/micro/tools/dev_setup/pre-push.tflm .git/hooks/pre-push
```

**Comment by gerbauz** [comment]
> We recently added Python formatting to the Code Style checks. Instructions on how to get that set up are at: https://github.com/tensorflow/tflite-micro/blob/main/CONTRIBUTING.md#initial-setup
> 
> You can fix all the formatting errors with:
> 
> ```
> tensorflow/lite/micro/tools/ci_build/test_code_style.sh --fix_formatting
> ```
> 
> Please note that you should delete the pigweed folder prior to trying this out:
> 
> ```
> rm -rf tensorflow/lite/micro/tools/make/downloads/pigweed
> ```
> 
> and add a pre-push hook with
> 
> ```
> cp tensorflow/lite/micro/tools/dev_setup/pre-push.tflm .git/hooks/pre-push
> ```

Hi Advait, sorry, this command do nothing for me. Tried on windows machine.

**Comment by gerbauz** [comment]
@advaitjain Figured that out, thank you.

**Comment by gerbauz** [comment]
Hi, @advaitjain can you please merge this one? Thank you!

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
