### PR TITLE
Cadence HiFi 4 Neural Network Library v2.4.1:

### PR DESCRIPTION
**Pull request by cad-audio**
Updated the script to download HiFi 4 Neural Network Library v2.4.1.
Removed the hifi4 patch
Updates in v2.4.1 library:
+ Fixed the issue related to special case handling in xa_nn_dot_prod_16x16_asym8s.
  Moved the special cases handling for vec_length=8/32 to the start of the function.
+ Removed legacy condition checks for depthwise_conv kernels.
+ Fixed the non-bit-exact issue related to xa_nn_conv2d_std_per_chan_sym8sxasym8s.
  updated to select correct vec values in case of vec_align_val is 1 and

BUG=#329

### CODE REVIEW

**Comment by cad-audio** [comment]
@advaitjain

**Comment by advaitjain** [comment]
Does this update also address https://github.com/tensorflow/tflite-micro/issues/329?

**Review by advaitjain — APPROVED** [review]

**Comment by cad-audio** [comment]
@advaitjain 
Yes, I have verified with the unit test case as well (which is attached in #329 )

**Comment by advaitjain** [comment]
> @advaitjain
> Yes, I have verified with the unit test case as well (which is attached in #329 )

Thanks!

**Pull request merged**
