### PR TITLE
Fixed EXT_CFLAGS option support for ARC.

### PR DESCRIPTION
**Pull request by gerbauz**
This PR brings small update for Makefile to support EXT_CFLAGS feature: https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/kernels/arc_mli#scratch-buffers-and-slicing.

BUG=#719

### CODE REVIEW

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated. @advaitjain, please review this one.

**Review by tingyan19 — APPROVED** [review]

**Pull request merged**
