### PR TITLE
Bug fixes in mli_interface and mli_tf_utils.

### PR DESCRIPTION
**Pull request by gerbauz**
This PR brings utils update for ARC target.

BUG=#719

### CODE REVIEW

**Review by petewarden — APPROVED** [review]

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated branch. Waiting for merge.

**Comment by gerbauz** [comment]
Updated.

**Pull request merged**
