### PR TITLE
build: update flatbuffers dependency to v23.5.26

### PR DESCRIPTION
**Pull request by rkuester**
Update the third_party flatbuffers library to v23.5.26, the
current version in upstream TF. Synchronize the override BUILD
and build_defs.bzl files with those from upstream TF at
e4485c98eae.

Also update the Makefile build, which downloads flatbuffers
separately. Rebase the patch applied to the download.

Regenerate the generated-and-checked-in schemas (see
ci/sync_from_upstream_tf.sh and codegen/preprocessor/
update_schema.sh), because they are stamped with the version of
the flatbuffers library, and fail a static_assert if they are
built with a different version of flatbuffers than they were
generated with.

BUG=unsuccessful attempt to fix warning in #2183

### CODE REVIEW

**Comment by rascani** [comment]
We also need to update the version downloaded as part of the make build: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/flatbuffers_download.sh#L57

**Review by rascani — APPROVED** [review]

**Comment by rkuester** [comment]
@rascani, the merge is failing for a reason I've not encountered before: https://github.com/tensorflow/tflite-micro/pull/2274/checks?check_run_id=17757924691. Can you please take a look?

**Comment by rascani** [comment]
@Mergifyio refresh

**Comment by rascani** [comment]
@Mergifyio refresh

**Pull request merged**
