### PR TITLE
REF_CODE_REFACTOR: Add, Mul and Sub

### LINKED ISSUE #122: Xtensa optimized kernels for add and mul
As noted in https://github.com/tensorflow/tflite-micro/pull/115#pullrequestreview-674750771 we will need some refactoring prior to adding in optimized implementations for add and mul for Xtensa.

This will include refactoring the reference and cmsis_nn kernels and then adding the Xtensa kernels with optimized calls for Hifi5 and reference fallback for all other target architectures.

### PR DESCRIPTION
**Pull request by cad-audio**
Refactoring the reference code for Add, Mul and Sub operators.

BUG=Fixes #122

### CODE REVIEW

**Comment by cad-audio** [comment]
@advaitjain

**Comment by petewarden** [comment]
Hi @cad-audio ! Could you file a bug to discuss the motivation for this and other refactoring? From inspection the individual changes seem to be reasonable, but since code churn has a cost too, it would be good to understand how you're deciding to make changes and what issues you're addressing.

**Comment by cad-audio** [comment]
Hi @petewarden,
refactoring is required to share the common code between reference and optimized kernels.
keep the shared structures and functions into operator_common.cc to avoid redundant code.

references for the code refactoring: [conv refactoring](https://github.com/tensorflow/tensorflow/commit/3aa4d9952c0bcf9e2ed7b7d5e79b3b68c4a809da) and [depthwise_conv refactoring](https://github.com/tensorflow/tensorflow/commit/e7bf37c70ea5d5c00789def52114190ca8fb6), which is done by tflm team.

@advaitjain, could you please comment on this.

**Comment by advaitjain** [comment]
> Hi @petewarden,
> refactoring is required to share the common code between reference and optimized kernels.
> keep the shared structures and functions into operator_common.cc to avoid redundant code.
> 
> references for the code refactoring: [conv refactoring](https://github.com/tensorflow/tensorflow/commit/3aa4d9952c0bcf9e2ed7b7d5e79b3b68c4a809da) and [depthwise_conv refactoring](https://github.com/tensorflow/tensorflow/commit/e7bf37c70ea5d5c00789def52114190ca8fb6), which is done by tflm team.
> 
> @advaitjain, could you please comment on this.

Apologies for the delay here. Yes, this refactoring is the first step in adding optimized kernel implementations.

https://github.com/tensorflow/tflite-micro/issues/122

@cad-audio, if you can resolve the conflicts then I will review and merge this PR early next week.

**Comment by bhanuprakashbv** [comment]
@advaitjain , resolved the conflicts.

**Review by advaitjain — APPROVED** [review]

**Review by advaitjain — APPROVED** [review]

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
