### PR TITLE
Removing ARC code related to examples and updating make files and test scripts.

### PR DESCRIPTION
**Pull request by gerbauz**
This PR removes ARC unused files (probably temporary) and contains some scripts to run tests for ARC target.

BUG=#637

### CODE REVIEW

**Comment by gerbauz** [comment]
Updated.

**Review by deqiangc — COMMENTED** [review]
@advaitjain 

This PR deletes the test in kernels such as tensorflow/micro/kernels/arc_mili/conv_slicing_test.cc.   Although this kind of test is not commonly seen and encouraged, I am not sure of removing them either.  I will defer to @advaitjain  for a second pair of eyes/thoughts.

**Comment by gerbauz** [comment]
> This PR deletes the test in kernels such as tensorflow/micro/kernels/arc_mili/conv_slicing_test.cc. Although this kind of test is not commonly seen and encouraged, I am not sure of removing them either. I will defer to @advaitjain for a second pair of eyes/thoughts.

Yes, this are tests specific to ARC slicing code. They haven't been updated for a long time, so we decided to remove them and maybe return back to them later.

**Comment by gerbauz** [comment]
Updated.

**Comment by gerbauz** [comment]
Updated.

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
