### PR TITLE
lstm:training micro speech lstm model

### PR DESCRIPTION
**Pull request by nyadla-sys**
BUG= training micro speech lstm model and example
Signed-off-by: Niranjan Yadla <nyadla@cadence.com>

### CODE REVIEW

**Comment by nyadla-sys** [comment]
@advaitjain, Could you please merge this change?

**Comment by advaitjain** [comment]
I have removed some of the files that should no longer be needed with https://github.com/tensorflow/tflite-micro/pull/473/commits/860877b1a571905cd78bc39e90962dd3b72746a0

There are some updates to the documentation as well as including the wav file to spectrogram conversion that will be addressed with follow-up PRs.

**Review by advaitjain — DISMISSED** [review]

**Review by advaitjain — CHANGES_REQUESTED** [review]
One last remaining item is that we will need to add a separate LICENSE file to third_party/xtensa.

I'm assuming that since this started out as a contribution into tensorflow/lite/micro, we can use the tflite-micro LICENSE: https://github.com/tensorflow/tflite-micro/blob/main/LICENSE

Let me know what you think.

**Comment by nyadla-sys** [comment]
@advaitjain, I have just updated LICENSE file to xtensa folder
Please review and merge #438 PR

**Review by advaitjain — APPROVED** [review]

**Pull request merged**
